# Generated by Django 4.2.6 on 2024-01-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_car_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=200, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, null=True)),
                ("invoice_url", models.CharField(max_length=100, null=True)),
                ("status", models.CharField(max_length=100, null=True)),
                ("order", models.ManyToManyField(to="store.order")),
            ],
        ),
    ]
