# Generated by Django 4.2.6 on 2024-02-01 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_monosettings_orderinvoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderinvoice",
            old_name="order",
            new_name="orders",
        ),
    ]
